function dataderiv = numderiv_centraldiff(data, deltat, derivOrder)

if derivOrder == 1
    dataderiv = [data(:,2)-data(:,1), (data(:,3:end)-data(:,1:end-2))/2, data(end)-data(end-1)]/deltat;
else
    dataderiv_4th = (-data(:,5:end)+16*data(:,4:end-1)-30*data(:,3:end-2)+16*data(:,2:end-3)-data(:,1:end-4))/(12*deltat^2);
    dataderiv_2nd = (data(:,3:end)+data(:,1:end-2)-2*data(:,2:end-1))/deltat^2;
    dataderiv = [dataderiv_2nd(:,1), ...
                 dataderiv_2nd(:,1), ...
                 dataderiv_4th, ...
                 dataderiv_2nd(:,1), ...
                 dataderiv_2nd(:,1)];
end